crminal/crm/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
#from viewsets import ModelViewSet
from . import views
from .views import *
from .models import Stage, Company, Contact, Campaign, Opportunity, Reminder, Report, CallLog, OpportunityStage

urlpatterns = [
    url(r'^$', login_required(views.Dashboard.as_view()), name="dashboard"),
 
    url(r'^search/$', login_required(views.SearchResults.as_view()), name="search"),

    url(r'^reports/$', login_required(views.Reports.as_view()), name="reports"),
 
    url(r'^stages/$', login_required(views.StageList.as_view()), name="stage_list"),
    url(r'^stages/(?P<pk>\d+)/$', login_required(views.StageDetail.as_view()), name="stage_detail"),
    url(r'^stages/create/$', login_required(views.CreateStage.as_view()), name="stage_create"),
    url(r'^stages/(?P<pk>\d+)/update/$', login_required(views.UpdateStage.as_view()), name="stage_update"),
    url(r'^stages/(?P<pk>\d+)/delete/$', login_required(views.DeleteStage.as_view()), name="stage_delete"),
	
    url(r'^companies/$', login_required(views.CompanyList.as_view()), name="company_list"),
    url(r'^companies/(?P<pk>\d+)/$', login_required(views.CompanyDetail.as_view()), name="company_detail"),
    url(r'^companies/create/$', login_required(views.CreateCompany.as_view()), name="company_create"),
    url(r'^companies/(?P<pk>\d+)/update/$', login_required(views.UpdateCompany.as_view()), name="company_update"),
    url(r'^companies/(?P<pk>\d+)/delete/$', login_required(views.DeleteCompany.as_view()), name="company_delete"),
    
    url(r'^contacts/$', login_required(views.ContactList.as_view()), name="contact_list"),
    url(r'^contacts/(?P<pk>\d+)/$', login_required(views.ContactDetail.as_view()), name="contact_detail"),
    url(r'^contacts/create/$', login_required(views.CreateContact.as_view()), name="contact_create"),
    url(r'^contacts/(?P<pk>\d+)/update/$', login_required(views.UpdateContact.as_view()), name="contact_update"),
    url(r'^contacts/(?P<pk>\d+)/delete/$', login_required(views.DeleteContact.as_view()), name="contact_delete"),
	
    url(r'^campaigns/$', login_required(views.CampaignList.as_view()), name="campaign_list"),
    url(r'^campaigns/(?P<pk>\d+)/$', login_required(views.CampaignDetail.as_view()), name="campaign_detail"),
    url(r'^campaigns/create/$', login_required(views.CreateCampaign.as_view()), name="campaign_create"),
    url(r'^campaigns/(?P<pk>\d+)/update/$', login_required(views.UpdateCampaign.as_view()), name="campaign_update"),
    url(r'^campaigns/(?P<pk>\d+)/delete/$', login_required(views.DeleteCampaign.as_view()), name="campaign_delete"),
   
    url(r'^opportunities/$', login_required(views.OpportunityList.as_view()), name="opportunity_list"),
    url(r'^opportunities/(?P<pk>\d+)/$', login_required(views.OpportunityDetail.as_view()), name="opportunity_detail"),
    url(r'^opportunities/create/$', login_required(views.CreateOpportunity.as_view()), name="opportunity_create"),
    url(r'^opportunities/(?P<pk>\d+)/update/$', login_required(views.UpdateOpportunity.as_view()), name="opportunity_update"),
    url(r'^opportunities/(?P<pk>\d+)/delete/$', login_required(views.DeleteOpportunity.as_view()), name="opportunity_delete"),

    url(r'^reminders/$', login_required(views.ReminderList.as_view()), name="reminder_list"),
    url(r'^reminders/(?P<pk>\d+)/$', login_required(views.ReminderDetail.as_view()), name="reminder_detail"),
    url(r'^reminders/create/$', login_required(views.CreateReminder.as_view()), name="reminder_create"),
    url(r'^reminders/(?P<pk>\d+)/update/$', login_required(views.UpdateReminder.as_view()), name="reminder_update"),
    url(r'^reminders/(?P<pk>\d+)/delete/$', login_required(views.DeleteReminder.as_view()), name="reminder_delete"),

    url(r'^calllogs/$', login_required(views.CallLogList.as_view()), name="calllog_list"),
    url(r'^calllogs/(?P<pk>\d+)/$', login_required(views.CallLogDetail.as_view()), name="calllog_detail"),
    url(r'^calllogs/create/$', login_required(views.CreateCallLog.as_view()), name="calllog_create"),
    url(r'^calllogs/(?P<pk>\d+)/update/$', login_required(views.UpdateCallLog.as_view()), name="calllog_update"),
    url(r'^calllogs/(?P<pk>\d+)/delete/$', login_required(views.DeleteCallLog.as_view()), name="calllog_delete"),

    url(r'^opportunitystages/(?P<pk>\d+)/$', login_required(views.OpportunityStageDetail.as_view()), name="opportunitystage_detail"),
]

crminal/crminal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('crm.urls', namespace='crm')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crminal/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
import datetime

class Stage(models.Model):
    name = models.CharField(max_length=200)
    order = models.IntegerField(help_text = 'The order this is displayed on the screen')
    description = models.TextField(blank=True, null=True)
    value = models.IntegerField(help_text = 'On a scale of 0 to 100 of the stage of the pipeline')

    def __unicode__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('crm:stage_index')

class Company(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField(max_length=200, blank=True, null=True)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=200, blank=True, null=True)

    def __unicode__(self):
        return str(self.name)

    class Meta:
        verbose_name_plural = "companies"

class Contact(models.Model):
    company = models.ForeignKey(Company, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True)

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __unicode__(self):
        return str(self.get_full_name())

class Campaign(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return str(self.name)

class Opportunity(models.Model):
    stage = models.ForeignKey(Stage)
    company = models.ForeignKey(Company, blank=True, null=True)
    contact = models.ForeignKey(Contact)
    value = models.DecimalField(help_text="How much this opportunity is worth to the organization", max_digits=10, decimal_places=2)
    source = models.ForeignKey(Campaign, help_text="How did this contact find out about this?")
    user = models.ForeignKey(User, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        if self.company:
            return str(self.company)
        else:
            return str(self.contact)

    def get_absolute_url(self):
        return reverse('crm:opportuny_index')

    class Meta:
        verbose_name_plural = "opportunities"


class Reminder(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    date = models.DateField()
    note = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s: %s" % (self.opportunity, self.note)

class Report(models.Model):
    name = models.CharField(max_length=200)
    link = models.URLField()

    def __unicode__(self):
        return str(self.name)

class CallLog(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    date = models.DateTimeField(auto_now_add=True)
    note = models.TextField()
    user = models.ForeignKey(User)

    def __unicode__(self):
        if self.user.get_full_name():
            return "%s on %s by %s" % (self.opportunity, self.date.strftime("%Y-%m-%d"), self.user.get_full_name())
        else:
            return "%s on %s by %s" % (self.opportunity, self.date.strftime("%Y-%m-%d"), self.user)


class OpportunityStage(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    stage = models.ForeignKey(Stage)
    time_stamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return "%s moved to %s" % (self.opportunity, self.stage)

crminal/crm/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget = forms.Textarea)

crminal/crm/views.py
#from django.http import HttpResponseRedirect
#from django import forms
#from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic import FormView, ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.db.models import Count, Q
import datetime
from itertools import chain
#from viewsets import ModelViewSet
from .models import Stage, Company, Contact, Campaign, Opportunity, Reminder, Report, CallLog, OpportunityStage

# Create your views here.
class Dashboard(ListView):
    model = OpportunityStage
    template_name = "crm/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)

        #AddingOpportunityStages to the template's context
	context["opportunity_stages"] = OpportunityStage.objects.all().order_by('-time_stamp')[:5]
	context["reminders"] = Reminder.objects.all().order_by('-date')[:5]
	context["opp_users"] = User.objects.filter(opportunitystage__stage__value = 100).annotate(num_opp=Count('opportunitystage'))[:5]
	context["stage_by_opp"] = Stage.objects.order_by('-order').annotate(opp_count = Count('opportunity'))
	context["opportunity_list"] = Opportunity.objects.all().order_by('-create_date')[:5]

	return context

class SearchResults(TemplateView):
    template_name = 'crm/search_results.html'
    def get_context_data(self, **kwargs):
	context = super(SearchResults, self).get_context_data(**kwargs)

        # If we don't have a search term in the URL, just return the context as is.
	# Otherwise, populate the template context with potential search results.

	if not self.request.GET.get("q", None):
	    return context

	term = self.request.GET["q"] # save off the search term for convenience
	context['searchterm'] = term # send the search term to the template's context
	context['contact_list'] = Contact.objects.all().filter(
	    Q(first_name__icontains = term) | Q(last_name__icontains = term))
	context['company_list'] = Company.objects.all().filter(name__icontains = term)
	context['reminder_list'] = Reminder.objects.all().filter(note__icontains = term)
	context['calllog_list'] = CallLog.objects.all().filter(note__icontains = term)
	context['opportunity_list'] = Opportunity.objects.all().filter(
	    Q(contact__first_name__icontains = term) | Q(contact__last_name__icontains = term) | Q(stage__name__icontains = term))
	return context

class Reports(ListView):
    model = Report
    template_name = "reports/dashboard.html"

class StageList(ListView):
    model = Stage
    queryset = Stage.objects.order_by('order')

class StageDetail(DetailView):
    model = Stage

class CreateStage(CreateView):
    model = Stage
    fields = ['name', 'order', 'description', 'value']
    success_url = reverse_lazy('crm:stage_list')

class UpdateStage(UpdateView):
    model = Stage
    fields = ['name', 'order', 'description', 'value']
    success_url = reverse_lazy('crm:stage_list')

class DeleteStage(DeleteView):
    model = Stage
    success_url = reverse_lazy('crm:stage_list')

class CompanyList(ListView):
    model = Company

class CompanyDetail(DetailView):
    model = Company

class CreateCompany(CreateView):
    model = Company
    fields = ['name', 'website', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone']
    success_url = reverse_lazy('crm:company_list')

class UpdateCompany(UpdateView):
    model = Company
    fields = ['name', 'website', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone']
    success_url = reverse_lazy('crm:company_list')

class DeleteCompany(DeleteView):
    model = Company
    success_url = reverse_lazy('crm:company_list')

class ContactList(ListView):
    model = Contact

class ContactDetail(DetailView):
    model = Contact

class CreateContact(CreateView):
    model = Contact
    fields = ['company', 'first_name', 'last_name', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone', 'email']
    success_url = reverse_lazy('crm:contact_list')

class UpdateContact(UpdateView):
    model = Contact
    fields = ['company', 'first_name', 'last_name', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone', 'email']
    success_url = reverse_lazy('crm:contact_list')

class DeleteContact(DeleteView):
    model = Contact
    success_url = reverse_lazy('crm:contact_list')

class CampaignList(ListView):
    model = Campaign

class CampaignDetail(DetailView):
    model = Campaign

class CreateCampaign(CreateView):
    model = Campaign
    fields = ['name', 'description']
    success_url = reverse_lazy('crm:campaign_list')

class UpdateCampaign(UpdateView):
    model = Campaign
    fields = ['name', 'description']
    success_url = reverse_lazy('crm:campaign_list')

class DeleteCampaign(DeleteView):
    model = Campaign
    success_url = reverse_lazy('crm:campaign_list')

class OpportunityList(ListView):
    model = Opportunity

    def get_context_data(self, **kwargs):
        context = super(OpportunityList, self).get_context_data(**kwargs)

        #Adding OpportunityStages to the templates' context
        context["opportunity_stages"] = OpportunityStage.objects.all()

        return context

class OpportunityDetail(DetailView):
    model = Opportunity

class CreateOpportunity(CreateView):
    model = Opportunity
    fields = ['stage', 'company', 'contact', 'value', 'source', 'user']
    success_url = reverse_lazy('crm:opportunity_list')

class UpdateOpportunity(UpdateView):
    model = Opportunity
    fields = ['stage', 'company', 'contact', 'value', 'source', 'user']
    success_url = reverse_lazy('crm:opportunity_list')

    def form_valid(self, form):
        opportunity = form.save(commit=False)

        #Checks to make sure the stage being moved to is the next stage and not a previous stage
        if opportunity.stage.value != self.get_object().stage.value:
            opportunity_stage = OpportunityStage()
            opportunity_stage.opportunity = Opportunity.objects.all().filter(id = self.get_object().pk)[0]
	    opportunity_stage.stage = form.cleaned_data['stage']
	    opportunity_stage.user = self.request.user
	    opportunity_stage.save()
        opportunity.save()
        return super(UpdateOpportunity, self).form_valid(form)

class DeleteOpportunity(DeleteView):
    model = Opportunity
    success_url = reverse_lazy('crm:opportunity_list')

class ReminderList(ListView):
    model = Reminder
    queryset = Reminder.objects.order_by('complete').order_by('-date')

class ReminderDetail(DetailView):
    model = Reminder

class CreateReminder(CreateView):
    model = Reminder
    fields = ['opportunity', 'date', 'note', 'completed']
    success_url = reverse_lazy('crm:reminder_list')

class UpdateReminder(UpdateView):
    model = Reminder
    fields = ['opportunity', 'date', 'note', 'completed']
    success_url = reverse_lazy('crm:reminder_list')

class DeleteReminder(DeleteView):
    model = Reminder
    success_url = reverse_lazy('crm:reminder_list')

class CallLogList(ListView):
    model = CallLog

class CallLogDetail(DetailView):
    model = CallLog

class CreateCallLog(CreateView):
    model = CallLog
    fields = ['opportunity', 'note', 'user']
    success_url = reverse_lazy('crm:calllog_list')

class UpdateCallLog(UpdateView):
    model = CallLog
    fields = ['opportunity', 'note', 'user']
    success_url = reverse_lazy('crm:calllog_list')

class DeleteCallLog(DeleteView):
    model = CallLog
    success_url = reverse_lazy('crm:calllog_list')

class OpportunityStageDetail(DetailView):
    model = OpportunityStage

crminal/crm/templates/crm/bad/dashboard.html
{% extends 'base.html' %}
{% block title %}CRM Dashboard{% endblock %}
{% block extrascripts %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Task', 'Hours per Day'],
                ['Work',               11],
                ['Eat',         2],
                ['Commute',     2],
                ['Watch TV',        2],
                ['Sleep',               7]
            ]);

            var options = {
                // title: 'My Daily Activities'
                // legend: 'none',
                is3D: true,
            };

			var chart = new google.visualization.PieChart(document.getElementByID('piechart'));
            chart.draw(data, options);
        }
    </script>
{% endblock extrascripts %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="jumbotron">
                <h1><a>TRIMAS, Inc. CRM</a></h1>
                <p>Three times the power of a normal relationship</p>
            </div>
       </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Upcoming Reminders
                        <span class="text-right pull-right">
                            <a href="#" class="btn btn-primary btn-sm mdi-action-list" style = "margin-top: -7px;" title = "List all Opportunities"></a>
                        </span>
                </div>

                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Opportunity</th>
                                <th>Note</th>
                                <th>Due Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><a href="#">Dire Wolf</a></td>
                                <td>How is winter at Yellowstone going?</td>
                                <td>15 Jan 2016</td>
                            </tr>
                            <tr>
                                <td><a href="#">Bottlenose Dolphin</a></td>
                                <td>How are you always so happy?</td>
                                <td>26 Nov 2015</td>
                            </tr>
                            <tr>
                                <td><a href="#">Peregrine Falcon</a></td>
                                <td>How do I find a lifelong companion?</td>
                                <td>10 Apr 2016</td>
                            </tr>
                            <tr>
                                <td><a href="#">Me</a></td>
                                <td>How are classes going?</td>
                                <td>23 Nov 2015</td>
                            </tr>
                    </table>
                    <div class="pull-right">
                        <a href="#" class="btn btn-primary btn-fab btn-raised mdi-content-add-box text-right" title="Create New Reminder"></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Newest Opportunities
                        <span class="text-right pull-right">
                            <a href="#" class="btn btn-primary btn-sm mdi-action-list" style = "margin-top: -7px;" title="List All Opportunities"></a>
                        </span>
                </div>

                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Opportunity</th>
                                <th>Stage</th>
                                <th>Value</th>
                                <th>Creation Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><a href="#" class="text-info">Dire Wolf</a></td>
                                <td>Closed - Success</td>
                                <td>$34,563</td>
                                <td>20 Apr 1995</td>
                            </tr>
                            <tr>
                                <td><a href="#" class="text-info">Bottlenose Dolphin</a></td>
                                <td>Proposal Sent</td>
                                <td>$2,063,312</td>
                                <td>19 Jul 2013</td>
                            </tr>
                                <td><a href="#">Peregrine Falcon</a></td>
                                <td>Closed - Success</td>
                                <td>$37,246</td>
                                <td>14 Dec 1974</td>
                            </tr>
                            <tr>
                                <td><a href="#">Me</a></td>
                                <td>Lead</td>
                                <td>$10,000</td>
                                <td>16 Feb 1994</td>
                            </tr>
                    </table>
                    <div class="pull-right">
                        <a href="#" class="btn btn-primary btn-fab btn-raised mdi-content-add-box text-right" title="Create New Opportunity"></a>
                    </div>
                </div>
	    </div>
	</div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Opportunities By Stage
                        <span class="text-right pull-right">
                            <a href="#" class="btn btn-primary btn-sm mdi-action-list" style = "margin-top: -7px;" title = "List all Opportunities"></a>
                        </span>
                </div>

                <div class="panel-body">
		    <div id="piechart" style="height: 500px;"></div>
		</div>
	    </div>
	</div>

        <div class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Top Producers
                        <span class="text-right pull-right">
                            <a href="#" class="btn btn-primary btn-sm mdi-action-list" style = "margin-top: -7px;" title="List All Opportunities"></a>
                        </span>
                </div>

                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Opportunities Closed</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>John Doe</td>
                                <td>43</td>
                            </tr>
                            <tr>
                                <td>Jane Doe</td>
                                <td>24</td>
                            </tr>
                                <td>Johnny Smith</td>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td><a href="#">Me</a></td>
                                <td>15</td>
                            </tr>
			</tbody>
                    </table>
                </div>
	    </div>
	</div>
    </div>
{% endblock content %}

crminal/crm/templates/crm/bad/opportunity_list2.html
{% extends 'base.html' %}
{% block title %}CRM Opportunity Dashboard{% endblock %}
{% block extrascripts %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="jumbotron">
            <h1>{{ opportunity }} ({{ opportunity.stage }})</h1>





{% endblock content %}

crminal/crm/templates/crm/bad/opportunity_list3.html
{% extends 'base.html' %}
{% block title %}Opportunities{% endblock title %}
{% block content %}
    <h1>Opportunity List</h1>
    <a class="btn btn-success" style="margin-top: -45px; float:right;" href="{% url 'crm:opportunity_create' %}">Add a New Opportunity</a>
    <div class="row">
        <div class="list-group col-lg-6" style="margin-top:10px;">
            {% for opportunity in opportunity_list %}
	        <a class="list-group-item" href="{% url 'crm:opportunity_detail' opportunity.id %}">{{ opportunity }} <span style="float:right;">Stage: {{ opportunity.stage }}</span></a>
	    {% endfor %}
        </div>

        <h1>Opportunity Stage Log</h1>
	<div class="list-group col-lg-6">
	    {% for opps in opportunity_stages %}
	        <a class="list-group-item" href="{% url 'crm:opportunitystage_detail' opps.id %}">{{ opps }}<span style="float:right;">{{ opps.time_stamp }}</span></a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}