suggestionbox/kaizen/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView
from . import views

urlpatterns = [
   url(r'^$', login_required(views.IdeaListView.as_view()), name="idealist"),
   url(r'^idea/(?P<pk>[0-9]+)/$', login_required(views.IdeaDetailView.as_view()), name="ideadetail"),
   url(r'^idea/add/$', views.CreateIdeaView.as_view(), name="addidea"),
   url(r'^idea/(?P<pk>[0-9]+)/update/$', views.UpdateIdeaView.as_view(), name="ideaupdate"),
   url(r'^idea/(?P<pk>[0-9]+)/delete/$', views.DeleteIdeaView.as_view(), name="deleteidea"),
   url(r'^idea/delete/success/$', TemplateView.as_view(template_name="kaizen/idea_delete_success.html"), name="deleteideasuccess"),
   url(r'^comment/submit/$', views.AddCommentView.as_view(), name="submitcomment"),
   url(r'^comment/submit/success$', TemplateView.as_view(template_name="kaizen/comment_success.html"), name="comment_success"),
   url(r'^(?P<pk>[0-9]+)/$', views.ChangeStatusView.as_view(), name="changestatus"),
]

suggestionbox/suggestionbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('kaizen.urls', namespace="kaizen")),
    url(r'^accounts/', include('userena.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

suggestionbox/kaizen/models.py
from django.db import models
from django.contrib.auth.models import User
from userena.models import UserenaBaseProfile

STATUS = (
    ('new', 'New'),
    ('den', 'Denied'),
    ('rev', 'In Review'),
    ('2d0', 'To Do'),
    ('doi', 'Doing'),
    ('imp', 'Implimented'),
)

# Create your models here.
class Profile(UserenaBaseProfile):
    user = models.ForeignKey(User)
    is_admin = models.BooleanField(default=False)

    def __unicode__(self):
        return self.user.get_full_name() or self.user.username()

class Idea(models.Model):
    profile = models.ForeignKey(Profile)
    title = models.CharField(max_length=200)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=3,
        choices=STATUS)
    category = models.ForeignKey('Category')

    def __unicode__(self):
        return self.title

class Category(models.Model):
    title = models.CharField(max_length=200)

    def __unicode__(self):
        return self.title

class Comment(models.Model):
    comment_text = models.TextField()
    idea = models.ForeignKey(Idea)
    pub_date = models.DateTimeField(auto_now_add=True)

suggestionbox/kaizen/forms.py
from django import forms

class CommentForm(forms.Form):
    person = forms.CharField(max_length=200, label="Name")
    comment_text = forms.CharField(widget=forms.Textarea, label="comment")
    idea_id = forms.IntegerField(widget=forms.HiddenInput)

suggestionbox/kaizen/views.py
from django.shortcuts import render
from .models import Idea, Category
from django.views.generic import ListView, DetailView
# Create your views here.
class IdeaListView(ListView):
    model = Idea

class SecretView(TemplateView):
    template_name="kaizen/secrets.html"

suggestionbox/kaizen/templates/kaizen/comment_success.html
{% extends 'base.html' %}

{% block title %}Thank You{% endblock title %}

{% block content %}
    <div class="alert alert-success">Thank you for your suggestion.</div>
{% endblock content %}

suggestionbox/kaizen/templates/kaizen/idea_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Idea{% endblock %}

{% block content %}
    <h1>Delete {{ idea.title }}</h1>
    {% ifequal idea.profile.user request.user %}
        <p>Are you sure you want to delte {{ idea }}?</p>
        <form action="{% url 'kaizen:deleteidea' idea.id %}" method='post'>
            {% csrf_token %}
            <table class="table">
                {{ form }}
                <tr>
                    <td colspan="2"><input type="submit" value="Delete Idea"></td>
                    <td colspan="2"><a href="..">Cancel</a></td>
                </tr>
            </table>
        </form>
    {% else %}
        <p>You don't have permission to delete this idea.</p>
        <a href="..">Cancel</a>
    {% endifequal %}
{% endblock content %}    

suggestionbox/kaizen/templates/kaizen/idea_delete_success.html
{% extends 'base.html' %}

{% block title %}Idea Removed{% endblock title %}

{% block content %}
    <div class="alert alert-success">Idea removal successful.</div>
{% endblock content %}

suggestionbox/kaizen/templates/kaizen/idea_detail.html
{% extends 'base.html' %}

{% block title %}Idea Page{% endblock %}

{% block content %}
    <h2>
        {{ idea.title }}
        {% ifequal idea.profile.user request.user %}
            <a href="{% url 'kaizen:updateidea' idea.id %}"><span class="glyphicon glyphicon-edit"></span></a>
            <a href="{% url 'kaizen:deleteidea' idea.id %}"><span style="color:red; margin-left:10px;" class="glyphicon glyphicon-remove"></span></a>
        {% endifequal %}
    </h2>
    <h4>Submitted by {{ idea.profile }} on {{ idea.pub_date|date:"m/d/Y" }}</h4>
    <p>{{ idea.description }}</p>
    <table class="table">
        <tr>
            <td>Category:<span style="margin-left:20px;">{{ idea.category.title }}</span></td>
        </tr>
        <tr>
            <td>Status:<span style="margin-left:20px;"> {{ idea.get_status_display }}</span></td>
        </tr>
    </table>
    <table id="comment-table" class="table table-bordred table-striped table-condensed">
        {% for comment in idea.comment_set.all reversed %}
            <h4>On {{ comment.pub_date|date:"M d, Y h:m:s"}}, {{ comment.person }} commented:</h4>
	    <div class="well">
	        {{ comment.comment_text }}
            </div>
            {% if not forloop.last %}
                <hr>
	    {% endif %}
	{% empty %}
	    <br>
	        <p>Be the first to comment on this idea.</p>
            <br>
	{% endfor %}
    </table>
    <form  action="{% url 'kaizen:submitcomment' %}" method="post"> {% csrf_token %}
        <table class="table table-condensed">
            {{ form }}
        </table>
        <button style="background:green; color:white" type="submit" class="btn btn-default">Add Comment</button>
    </form>
{% endblock %}

suggestionbox/kaizen/templates/kaizen/idea_form.html
{% extends 'base.html' %}

{% block title %}{% if idea %}Update{% else %}Add{% endif %} An Idea{% endblock %}

{% block content %}
    <h1>{% if idea %}Update{% else %}Add{% endif %} {{ idea.title }}</h1>
    <form action="." method="post">
        {% csrf_token %}
        <table class="table">
            {{ form }}
        </table>
        <input class="add-btn" type="submit" value="{% if idea %}Update{% else %}Add{% endif %} Idea">
        <span style="margin-left:10px;"><a href="/">Cancel</a>
    </form>
{% endblock content %}

suggestionbox/kaizen/templates/kaizen/idea_list.html
{% extends 'base.html' %}

{% block title %}List of Kaizens{% endblock %}

{% block content %}
    <h1>List of User-submitted Kaizens</h1>

    {% for idea in idea_list %}
        <div {% ifequal idea.profile.user request.user %}class="mark"{% endifequal %}</div>
        <a href="{% url 'kaizen:ideadetail' idea.id %}">
            <h3>{{ idea.title }}</h3>
        </a>
        <h4>Submitted by {{ idea.profile }} on {{ idea.pub_date|date:"m/d/Y" }}</h4>
        <p>
            {{ idea.description }}
        </p>
        <table class="table">
        <tr>
            <td>Category:<span style="margin-left:20px;">{{ idea.category.title }}</span></td>
        </tr>
        <tr>
            <td>Status:<span style="margin-left:20px;">
                {% if request.user.is_superuser %}
                    <a href="{% url 'kaizen:changestatus' idea.id %}">
                        {{ idea.get_status_display }} - change
                    </a>
                {% else %}
                    {{ idea.get_status_display }}
                {% endif %}
		</span>
            </td>
        </tr>
        </table>
        </div>
    {% empty %}
        <p>No kaizens submited yet. Want to <a href="{% url 'kaizen:addidea' %}">submit one?</a></p>
    {% endfor %}
    <a href="{% url 'kaizen:addidea' %}"><span style="color:green; margin-right:7px;" class="glyphicon glyphicon-plus"></span></a><span>Add a new kaizen</span>
{% endblock %}

suggestionbox/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Inventory Catalog Site">
    <meta name="author" content="Sarah Stander">

    <title>{% block title %}Kaizen{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <link rel="stylesheet" href="/media/style.css">
  <style>
  .errorlist {
     color:red;
     list-style-type: none;
  }
  </style>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  {% block extrascripts %}{% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Kaizen</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/admin/">Admin</a></li>
            <li><a href="mailto:sarahtstander@gmail.com">Contact</a></li>
            <li>
                {% if request.user.is_authenticated %}
                    <a href="/accounts/signout/">Log Out</a>
                {% else %}
                    <a href="/accounts/signin/">Log In</a>
                {% endif %}
            </li>
            {% ifnotequal AnonymousUser request.user %}
                <li>
                    <a href="/accounts/{{request.user}}" style="color:white;">Logged in as {{ request.user }}</a>
                </li>
            {% endifnotequal %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" style="margin-top: 50px;">
{% block content %}

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>
{% endblock %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

suggestionbox/templates/userena/activate_retry.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}


{% block title %}{% trans "Account activation failed." %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account could not be activated..." %}</h2>{% endblock %}

{% block content %}
<p>{% trans "Your account could not be activated because activation link is expired." %}</p>
<p><a href="{% url 'userena_activate_retry' activation_key %}">{% trans "Request a new activation link." %}</a></p>
{% endblock %}

suggestionbox/templates/userena/activate_retry_success.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}


{% block title %}{% trans "Account re-activation succeeded." %}{% endblock %}
{% block content_title %}<h2>{% trans "Account re-activation" %}</h2>{% endblock %}

{% block content %}
<p>{% blocktrans %}You requested a new activation of your account..{% endblocktrans %}</p>
<p>{% blocktrans %}You have been sent an e-mail with an activation link to the supplied email.{% endblocktrans %}</p>
<p>{% blocktrans %}We will store your signup information for {{ userena_activation_days }} days on our server. {% endblocktrans %}</p>
{% endblock %}

suggestionbox/templates/userena/disabled.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Disabled account" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your account has been disabled" %}</h2>{% endblock %}
{% block content %}
<p>{% trans "It seems your account has been disabled." %}</p>
<p>{% trans "If you feel that injustice has been done to you, feel free to contact the administrators to find out why" %}</p>
{% endblock %} 

suggestionbox/templates/userena/email_change_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Email verification" %}{% endblock %}
{% block content_title %}<h2>{% trans 'Confirm your new email' %}</h2>{% endblock %}

{% block content %}
<p>{% blocktrans with viewed_user.userena_signup.email_unconfirmed as email %}You have received an email at {{ email }}.{% endblocktrans %}</p>
<p>{% blocktrans with viewed_user.username as username %}To associate this email address with your account ({{ username }}) click on the link provided in this email.{% endblocktrans %}</p>
{% endblock %}

suggestionbox/templates/userena/email_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block content_title %}<h2>{% blocktrans with user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}
<form action="" method="post">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last selected"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Change email address" %}</legend>
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Change email" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/password_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Password changed" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been changed" %}.</h2>{% endblock %}

{% block content %}
<p>{% trans "From now on you can use your new password to signin" %}.</p>
{% endblock %}

suggestionbox/templates/userena/password_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}
<form action="" method="post" id="password_change_form">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li  class="selected"><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  <fieldset>
    <legend>{% trans "Change Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Change password" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/password_reset_complete.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Password reset" %}{% endblock %}
{% block content_title %}<h2>{% trans "Your password has been reset" %}</h2>{% endblock %}
{% block content %}
{% url 'userena_signin' as signin_url %}
{% blocktrans %}You can now <a href="{{ signin_url }}">signin</a> with your new password.{% endblocktrans %}
{% endblock %}

suggestionbox/templates/userena/password_reset_confirm_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}
<form action="" method="post">
  <fieldset>
    <legend>{% trans "Reset Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Reset password" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/password_reset_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}

{% block title %}{% trans "Reset password" %}{% endblock %}

{% block content %}
<form action="" method="post">
  <fieldset>
    <legend>{% trans "Reset Password" %}</legend>
    {% csrf_token %}
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Send password" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/profile_detail.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% blocktrans with profile.user.username as username %}{{ username }}'s profile.{% endblocktrans %}{% endblock %}
{% block content_title %}<h2>{{ profile.user.username }} {% if profile.user.get_full_name %}({{ profile.user.get_full_name }}){% endif %}</h2>{% endblock %}

{% block content %}
  <div class="white-box">
    {% block profile_navigation %}
      {% comment %}Dirty hack. Will use django-guardian in the future.{% endcomment %}
      {% if user.username == profile.user.username %}
        <ul id="box-nav">
          {% block profile_navigation_items %}
            <li><a href="{% url 'userena_profile_detail' user.username %}">{% trans "View profile" %}</a></li>
            <li><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit details" %}</a></li>
            <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
            <li><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
          {% endblock %}
        </ul>
      {% endif %}
    {% endblock %}

    <div id="details">
      {% block profile_details %}
        <img class="mugshot" src="{{ profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" />
        <dl>
          {% block profile_definition_list %}
            {% if profile.user.get_full_name %}
              <dt>{% trans "Name" %}</dt>
              <dd>{{ profile.user.get_full_name }}</dd>
            {% endif %}
            {% if profile.user.email and not hide_email %}
              <dt>{% trans "Email" %}</dt>
              <dd>{{ profile.user.email }}</dd>
            {% endif %}
            {% if profile.age %}
              <dt>{% trans "Age" %}</dt>
              <dd>{{ profile.age }}</dd>
            {% endif %}
            {% if profile.website %}
              <dt>{% trans "Website" %}</dt>
              <dd>{{ profile.website|urlize }}</dd>
            {% endif %}
            {% if profile.location %}
              <dt>{% trans "Location" %}</dt>
              <dd>{{ profile.location }}</dd>
            {% endif %}
            {% if profile.about_me %}
              <dt>{% trans "About me" %}</dt>
              <dd>{{ profile.about_me }}</dd>
            {% endif %}
          {% endblock %}
        </dl>
      {% endblock %}
    </div>
  </div>
{% endblock %}

suggestionbox/templates/userena/profile_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Account setup" %}{% endblock %}

{% block content_title %}<h2>{% blocktrans with profile.user.username as username %}Account &raquo; {{ username }}{% endblocktrans %}</h2>{% endblock %}

{% block content %}

<form action="" enctype="multipart/form-data" method="post">
  <ul id="box-nav">
    <li class="first"><a href="{% url 'userena_profile_detail' user.username %}"><span>{% trans 'View profile' %}</span></a></li>
    <li class="selected"><a href="{% url 'userena_profile_edit' user.username %}">{% trans "Edit profile" %}</a></li>
    <li><a href="{% url 'userena_password_change' user.username %}">{% trans "Change password" %}</a></li>
    <li class="last"><a href="{% url 'userena_email_change' user.username %}">{% trans "Change email" %}</a></li>
  </ul>
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Edit Profile" %}</legend>
    {{ form.as_p }}
  </fieldset>
  <input type="submit" value="{% trans "Save changes" %}" />
</form>
{% endblock %}

suggestionbox/templates/userena/profile_list.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block content_title %}<h2>{% trans 'Profiles' %}</h2>{% endblock %}

{% block content %}
<ul id="profile_list">
  {% for profile in profile_list %}
  <li>
  <a href="{% url 'userena_profile_detail' profile.user.username %}"><img src="{{ profile.get_mugshot_url }}" /></a>
  <a href="{% url 'userena_profile_detail' profile.user.username %}">{{ profile.user.username }}</a>
  </li>
  {% endfor %}

</ul>

{% if is_paginated %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="{% url 'userena_profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
    {% endif %}

    <span class="current">
      {% blocktrans with page_obj.number as page and page_obj.paginator.num_pages as num_pages %}
      Page {{ page }} of {{ num_pages }}
      {% endblocktrans %}
    </span>

    {% if page_obj.has_next %}
    <a href="{% url 'userena_profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
    {% endif %}
  </span>
</div>
{% endif %}
{% endblock %}

suggestionbox/templates/userena/signin_form.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans "Signin" %}{% endblock %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>{% trans "Signin" %}</legend>
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.errors }}
    {% comment %} Displaying checkboxes differently {% endcomment %}
    {% if field.name == 'remember_me' %}
    <p class="checkbox">
    <label for="id_{{ field.name }}">{{ field }} {{ field.label }}</label>
    </p>
    {% else %}
    <p>
    {{ field.label_tag }}
    {{ field }}
    </p>
    {% endif %}
    {% endfor %}
  </fieldset>
  <input type="submit" value="{% trans "Signin" %}" /><span style="margin-left:20px;"><a class="btn btn-default" href="/accounts/signup/">Register</a>
  <p class="forgot-password"><a href="{% url 'userena_password_reset' %}" title="{% trans 'Forgot your password?' %}">{% trans "Forgot your password?" %}</a></p>
  {% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}
</form>
{% endblock %}