crminal/crm/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
#from viewsets import ModelViewSet
from . import views
from .views import *
from .models import Stage, Company, Contact, Campaign, Opportunity, Reminder, Report, CallLog, OpportunityStage

urlpatterns = [
    url(r'^$', login_required(views.Dashboard.as_view()), name="dashboard"),
 
    url(r'^search/$', login_required(views.SearchResults.as_view()), name="search"),

    url(r'^reports/$', login_required(views.Reports.as_view()), name="reports"),
 
    url(r'^stages/$', login_required(views.StageList.as_view()), name="stage_list"),
    url(r'^stages/(?P<pk>\d+)/$', login_required(views.StageDetail.as_view()), name="stage_detail"),
    url(r'^stages/create/$', login_required(views.CreateStage.as_view()), name="stage_create"),
    url(r'^stages/(?P<pk>\d+)/update/$', login_required(views.UpdateStage.as_view()), name="stage_update"),
    url(r'^stages/(?P<pk>\d+)/delete/$', login_required(views.DeleteStage.as_view()), name="stage_delete"),
	
    url(r'^companies/$', login_required(views.CompanyList.as_view()), name="company_list"),
    url(r'^companies/(?P<pk>\d+)/$', login_required(views.CompanyDetail.as_view()), name="company_detail"),
    url(r'^companies/create/$', login_required(views.CreateCompany.as_view()), name="company_create"),
    url(r'^companies/(?P<pk>\d+)/update/$', login_required(views.UpdateCompany.as_view()), name="company_update"),
    url(r'^companies/(?P<pk>\d+)/delete/$', login_required(views.DeleteCompany.as_view()), name="company_delete"),
    
    url(r'^contacts/$', login_required(views.ContactList.as_view()), name="contact_list"),
    url(r'^contacts/(?P<pk>\d+)/$', login_required(views.ContactDetail.as_view()), name="contact_detail"),
    url(r'^contacts/create/$', login_required(views.CreateContact.as_view()), name="contact_create"),
    url(r'^contacts/(?P<pk>\d+)/update/$', login_required(views.UpdateContact.as_view()), name="contact_update"),
    url(r'^contacts/(?P<pk>\d+)/delete/$', login_required(views.DeleteContact.as_view()), name="contact_delete"),
	
    url(r'^campaigns/$', login_required(views.CampaignList.as_view()), name="campaign_list"),
    url(r'^campaigns/(?P<pk>\d+)/$', login_required(views.CampaignDetail.as_view()), name="campaign_detail"),
    url(r'^campaigns/create/$', login_required(views.CreateCampaign.as_view()), name="campaign_create"),
    url(r'^campaigns/(?P<pk>\d+)/update/$', login_required(views.UpdateCampaign.as_view()), name="campaign_update"),
    url(r'^campaigns/(?P<pk>\d+)/delete/$', login_required(views.DeleteCampaign.as_view()), name="campaign_delete"),
   
    url(r'^opportunities/$', login_required(views.OpportunityList.as_view()), name="opportunity_list"),
    url(r'^opportunities/(?P<pk>\d+)/$', login_required(views.OpportunityDetail.as_view()), name="opportunity_detail"),
    url(r'^opportunities/create/$', login_required(views.CreateOpportunity.as_view()), name="opportunity_create"),
    url(r'^opportunities/(?P<pk>\d+)/update/$', login_required(views.UpdateOpportunity.as_view()), name="opportunity_update"),
    url(r'^opportunities/(?P<pk>\d+)/delete/$', login_required(views.DeleteOpportunity.as_view()), name="opportunity_delete"),

    url(r'^reminders/$', login_required(views.ReminderList.as_view()), name="reminder_list"),
    url(r'^reminders/(?P<pk>\d+)/$', login_required(views.ReminderDetail.as_view()), name="reminder_detail"),
    url(r'^reminders/create/$', login_required(views.CreateReminder.as_view()), name="reminder_create"),
    url(r'^reminders/(?P<pk>\d+)/update/$', login_required(views.UpdateReminder.as_view()), name="reminder_update"),
    url(r'^reminders/(?P<pk>\d+)/delete/$', login_required(views.DeleteReminder.as_view()), name="reminder_delete"),

    url(r'^calllogs/$', login_required(views.CallLogList.as_view()), name="calllog_list"),
    url(r'^calllogs/(?P<pk>\d+)/$', login_required(views.CallLogDetail.as_view()), name="calllog_detail"),
    url(r'^calllogs/create/$', login_required(views.CreateCallLog.as_view()), name="calllog_create"),
    url(r'^calllogs/(?P<pk>\d+)/update/$', login_required(views.UpdateCallLog.as_view()), name="calllog_update"),
    url(r'^calllogs/(?P<pk>\d+)/delete/$', login_required(views.DeleteCallLog.as_view()), name="calllog_delete"),

    url(r'^opportunitystages/(?P<pk>\d+)/$', login_required(views.OpportunityStageDetail.as_view()), name="opportunitystage_detail"),
]

crminal/crminal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('crm.urls', namespace='crm')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crminal/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
import datetime

class Stage(models.Model):
    name = models.CharField(max_length=200)
    order = models.IntegerField(help_text = 'The order this is displayed on the screen')
    description = models.TextField(blank=True, null=True)
    value = models.IntegerField(help_text = 'On a scale of 0 to 100 of the stage of the pipeline')

    def __unicode__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('crm:stage_index')

class Company(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField(max_length=200, blank=True, null=True)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=200, blank=True, null=True)

    def __unicode__(self):
        return str(self.name)

    class Meta:
        verbose_name_plural = "companies"

class Contact(models.Model):
    company = models.ForeignKey(Company, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True)

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __unicode__(self):
        return str(self.get_full_name())

class Campaign(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return str(self.name)

class Opportunity(models.Model):
    stage = models.ForeignKey(Stage)
    company = models.ForeignKey(Company, blank=True, null=True)
    contact = models.ForeignKey(Contact)
    value = models.DecimalField(help_text="How much this opportunity is worth to the organization", max_digits=10, decimal_places=2)
    source = models.ForeignKey(Campaign, help_text="How did this contact find out about this?")
    user = models.ForeignKey(User, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        if self.company:
            return str(self.company)
        else:
            return str(self.contact)

    def get_absolute_url(self):
        return reverse('crm:opportuny_index')

    class Meta:
        verbose_name_plural = "opportunities"


class Reminder(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    date = models.DateField()
    note = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s: %s" % (self.opportunity, self.note)

class Report(models.Model):
    name = models.CharField(max_length=200)
    link = models.URLField()

    def __unicode__(self):
        return str(self.name)

class CallLog(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    date = models.DateTimeField(auto_now_add=True)
    note = models.TextField()
    user = models.ForeignKey(User)

    def __unicode__(self):
        if self.user.get_full_name():
            return "%s on %s by %s" % (self.opportunity, self.date.strftime("%Y-%m-%d"), self.user.get_full_name())
        else:
            return "%s on %s by %s" % (self.opportunity, self.date.strftime("%Y-%m-%d"), self.user)


class OpportunityStage(models.Model):
    opportunity = models.ForeignKey(Opportunity)
    stage = models.ForeignKey(Stage)
    time_stamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return "%s moved to %s" % (self.opportunity, self.stage)

crminal/crm/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget = forms.Textarea)

crminal/crm/views.py
#from django.http import HttpResponseRedirect
#from django import forms
#from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic import FormView, ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.db.models import Count, Q
import datetime
from itertools import chain
#from viewsets import ModelViewSet
from .models import Stage, Company, Contact, Campaign, Opportunity, Reminder, Report, CallLog, OpportunityStage

# Create your views here.
class Dashboard(ListView):
    model = OpportunityStage
    template_name = "crm/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)

        #AddingOpportunityStages to the template's context
	context["opportunity_stages"] = OpportunityStage.objects.all().order_by('-time_stamp')[:5]
	context["reminders"] = Reminder.objects.all().order_by('-date')[:5]
	context["opp_users"] = User.objects.filter(opportunitystage__stage__value = 100).annotate(num_opp=Count('opportunitystage'))[:5]
	context["stage_by_opp"] = Stage.objects.order_by('-order').annotate(opp_count = Count('opportunity'))
	context["opportunity_list"] = Opportunity.objects.all().order_by('-create_date')[:5]

	return context

class SearchResults(TemplateView):
    template_name = 'crm/search_results.html'
    def get_context_data(self, **kwargs):
	context = super(SearchResults, self).get_context_data(**kwargs)

        # If we don't have a search term in the URL, just return the context as is.
	# Otherwise, populate the template context with potential search results.

	if not self.request.GET.get("q", None):
	    return context

	term = self.request.GET["q"] # save off the search term for convenience
	context['searchterm'] = term # send the search term to the template's context
	context['contact_list'] = Contact.objects.all().filter(
	    Q(first_name__icontains = term) | Q(last_name__icontains = term))
	context['company_list'] = Company.objects.all().filter(name__icontains = term)
	context['reminder_list'] = Reminder.objects.all().filter(note__icontains = term)
	context['calllog_list'] = CallLog.objects.all().filter(note__icontains = term)
	context['opportunity_list'] = Opportunity.objects.all().filter(
	    Q(contact__first_name__icontains = term) | Q(contact__last_name__icontains = term) | Q(stage__name__icontains = term))
	return context

class Reports(ListView):
    model = Report
    template_name = "reports/dashboard.html"

class StageList(ListView):
    model = Stage
    queryset = Stage.objects.order_by('order')

class StageDetail(DetailView):
    model = Stage

class CreateStage(CreateView):
    model = Stage
    fields = ['name', 'order', 'description', 'value']
    success_url = reverse_lazy('crm:stage_list')

class UpdateStage(UpdateView):
    model = Stage
    fields = ['name', 'order', 'description', 'value']
    success_url = reverse_lazy('crm:stage_list')

class DeleteStage(DeleteView):
    model = Stage
    success_url = reverse_lazy('crm:stage_list')

class CompanyList(ListView):
    model = Company

class CompanyDetail(DetailView):
    model = Company

class CreateCompany(CreateView):
    model = Company
    fields = ['name', 'website', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone']
    success_url = reverse_lazy('crm:company_list')

class UpdateCompany(UpdateView):
    model = Company
    fields = ['name', 'website', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone']
    success_url = reverse_lazy('crm:company_list')

class DeleteCompany(DeleteView):
    model = Company
    success_url = reverse_lazy('crm:company_list')

class ContactList(ListView):
    model = Contact

class ContactDetail(DetailView):
    model = Contact

class CreateContact(CreateView):
    model = Contact
    fields = ['company', 'first_name', 'last_name', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone', 'email']
    success_url = reverse_lazy('crm:contact_list')

class UpdateContact(UpdateView):
    model = Contact
    fields = ['company', 'first_name', 'last_name', 'address1', 'address2', 'city', 'state', 'zipcode', 'country', 'phone', 'email']
    success_url = reverse_lazy('crm:contact_list')

class DeleteContact(DeleteView):
    model = Contact
    success_url = reverse_lazy('crm:contact_list')

class CampaignList(ListView):
    model = Campaign

class CampaignDetail(DetailView):
    model = Campaign

class CreateCampaign(CreateView):
    model = Campaign
    fields = ['name', 'description']
    success_url = reverse_lazy('crm:campaign_list')

class UpdateCampaign(UpdateView):
    model = Campaign
    fields = ['name', 'description']
    success_url = reverse_lazy('crm:campaign_list')

class DeleteCampaign(DeleteView):
    model = Campaign
    success_url = reverse_lazy('crm:campaign_list')

class OpportunityList(ListView):
    model = Opportunity

    def get_context_data(self, **kwargs):
        context = super(OpportunityList, self).get_context_data(**kwargs)

        #Adding OpportunityStages to the templates' context
        context["opportunity_stages"] = OpportunityStage.objects.all()

        return context

class OpportunityDetail(DetailView):
    model = Opportunity

class CreateOpportunity(CreateView):
    model = Opportunity
    fields = ['stage', 'company', 'contact', 'value', 'source', 'user']
    success_url = reverse_lazy('crm:opportunity_list')

class UpdateOpportunity(UpdateView):
    model = Opportunity
    fields = ['stage', 'company', 'contact', 'value', 'source', 'user']
    success_url = reverse_lazy('crm:opportunity_list')

    def form_valid(self, form):
        opportunity = form.save(commit=False)

        #Checks to make sure the stage being moved to is the next stage and not a previous stage
        if opportunity.stage.value != self.get_object().stage.value:
            opportunity_stage = OpportunityStage()
            opportunity_stage.opportunity = Opportunity.objects.all().filter(id = self.get_object().pk)[0]
	    opportunity_stage.stage = form.cleaned_data['stage']
	    opportunity_stage.user = self.request.user
	    opportunity_stage.save()
        opportunity.save()
        return super(UpdateOpportunity, self).form_valid(form)

class DeleteOpportunity(DeleteView):
    model = Opportunity
    success_url = reverse_lazy('crm:opportunity_list')

class ReminderList(ListView):
    model = Reminder
    queryset = Reminder.objects.order_by('complete').order_by('-date')

class ReminderDetail(DetailView):
    model = Reminder

class CreateReminder(CreateView):
    model = Reminder
    fields = ['opportunity', 'date', 'note', 'completed']
    success_url = reverse_lazy('crm:reminder_list')

class UpdateReminder(UpdateView):
    model = Reminder
    fields = ['opportunity', 'date', 'note', 'completed']
    success_url = reverse_lazy('crm:reminder_list')

class DeleteReminder(DeleteView):
    model = Reminder
    success_url = reverse_lazy('crm:reminder_list')

class CallLogList(ListView):
    model = CallLog

class CallLogDetail(DetailView):
    model = CallLog

class CreateCallLog(CreateView):
    model = CallLog
    fields = ['opportunity', 'note', 'user']
    success_url = reverse_lazy('crm:calllog_list')

class UpdateCallLog(UpdateView):
    model = CallLog
    fields = ['opportunity', 'note', 'user']
    success_url = reverse_lazy('crm:calllog_list')

class DeleteCallLog(DeleteView):
    model = CallLog
    success_url = reverse_lazy('crm:calllog_list')

class OpportunityStageDetail(DetailView):
    model = OpportunityStage

crminal/crm/templates/crm/calllog_list.html
{% extends 'base.html' %}
{% block title %}Call Logs{% endblock title %}
{% block content %}
    <div class="row">
	<div class="col-lg-12">
	    <div class="panel panel-primary">
		<div class="panel-heading">	
		    List All Call Logs
		</div>
	    	<div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Opportunity</th>
                                <th>User</th>
                                <th>Note</th>
                                <th>Creation Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for calllog in calllog_list %}
				<tr>
				    <td><a href="{% url 'crm:calllog_detail' calllog.id %}" class="text-info">{{ calllog.opportunity }}</a></td>
				    <td>{{ calllog.user }}</td>
				    <td>{{ calllog.note }}</td>
				    <td>{{ calllog.date }}</td>
				</tr>
			    {% endfor %}
			</tbody>
		    </table>
		    <div class="pull-right">
			<a href="{% url 'crm:calllog_create' %}" class="btn btn-success btn-circle glyphicon glyphicon-plus" title="Create New calllog"></a>
		    </div>
		</div>
	    </div>
	</div>
    </div>
{% endblock content %}

crminal/crm/templates/crm/campaign_detail.html
{% extends 'base.html' %}
{% block title %}Campaign {{ campaign.name }}{% endblock title %}
{% block content %}
    <div class="row">
	<div class="col-lg-12">
	    <div class="panel panel-primary">
		<div class="panel-heading">	
		    Campaign {{ campaign.name }}
		</div>
	    	<div class="panel-body">
                    <table class="table table">
                        <thead>
                            <tr class="success">
                                <th>Name</th>
				<th>Description</th>
				<th>Edit</th>
				<th>Delete</th>
			    </tr>
			</thead>
		        <tbody>
			    <tr>
				<td>{{ campaign.name }}</td>
				<td>{{ campaign.description }}</td>
				<td><a href="{% url 'crm:campaign_update' campaign.id %}"><span style="color:blue;" class="glyphicon glyphicon-edit"></span></a></td>
				<td><a href="{% url 'crm:campaign_delete' campaign.id %}"><span style="color:red;" class="glyphicon glyphicon-remove"></span></a></td>
			    </tr>
			</tbody>
		    </table>
		    <a class="btn btn-success" style="float:right;" href="{% url 'crm:campaign_list' %}">Return to Campaign List?</a>
		</div>
	    </div>
	</div>
    </div>
{% endblock content %}

crminal/crm/templates/crm/contact_detail.html
{% extends 'base.html' %}
{% block title %}Contact {{ contact.get_full_name }}{% endblock title %}
{% block content %}
    <div class="row">
	<div class="col-lg-12">
	    <div class="panel panel-primary">
		<div class="panel-heading">	
		    Contact {{ contact.get_full_name }}
		</div>
	    	<div class="panel-body">
                    <table class="table table-striped">
                        <thead>
                            <tr class="success">
                                <th>Company</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Address 1</th>
				<th>Address 2</th>
                                <th>City</th>
				<th>State</th>
				<th>ZIP code</th>
				<th>Country</th>
                                <th>Phone</th>
				<th>Edit</th>
				<th>Delete</th>
			    </tr>
			</thead>
		        <tbody>
			    <tr>
				<td>{{ contact.company }}</td>
				<td>{{ contact.first_name }}</td>
				<td>{{ contact.last_name }}</td>
				<td>{{ contact.address1 }}</td>
				<td>{{ contact.address2 }}</td>
				<td>{{ contact.city }}</td>
				<td>{{ contact.state }}</td>
				<td>{{ contact.zipcode }}</td>
				<td>{{ contact.country }}</td>
				<td>{{ contact.phone }}</td>
				<td><a href="{% url 'crm:contact_update' contact.id %}"><span style="color:blue;" class="glyphicon glyphicon-edit"></span></a></td>
				<td><a href="{% url 'crm:contact_delete' contact.id %}"><span style="color:red;" class="glyphicon glyphicon-remove"></span></a></td>
			    </tr>
			</tbody>
		    </table>
		    <a class="btn btn-success" style="float:right;" href="{% url 'crm:contact_list' %}">Return to Contact List?</a>
		</div>
	    </div>
	</div>
    </div>
{% endblock content %}

crminal/crm/templates/crm/contact_list.html
{% extends 'base.html' %}
{% block title %}Contacts{% endblock title %}
{% block content %}
    <div class="row">
	<div class="col-lg-12">
	    <div class="panel panel-primary">
		<div class="panel-heading">	
		    List All Contacts
		</div>
	    	<div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Company</th>
				<th>First Name</th>
				<th>Last Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contact in contact_list %}
				<tr>
				    <td><a href="{% url 'crm:contact_detail' contact.id %}" class="text-info">{{ contact.company }}</a></td>
				    <td>{{ contact.first_name }}</td>
				    <td>{{ contact.last_name }}</td>
				</tr>
			    {% endfor %}
			</tbody>
		    </table>
		    <div class="pull-right">
			<a href="{% url 'crm:contact_create' %}" class="btn btn-success btn-circle glyphicon glyphicon-plus" title="Create New Contact"></a>
		    </div>
		</div>
	    </div>
	</div>
    </div>
{% endblock content %}

crminal/crm/templates/crm/opportunity_detail.html
{% extends 'base.html' %}
{% block title %}Opportunity {{ opportunity.company }}{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="jumbotron">
                <h1><a href="/">{{ opportunity.company }} ({{ opportunity.stage }})</a>
                <p class="pull-right">
		    <a href="{% url 'crm:opportunity_update' opportunity.id %}"><span class="glyphicon glyphicon-edit" style="color:blue; margin-right:20px;"</a>
		    <a href="{% url 'crm:opportunity_delete' opportunity.id %}"><span class="glyphicon glyphicon-remove" style="color:red;"></a></h1>
		</p>
            </div>
       </div>
    </div>
    <div class="row">
	<div class="col-lg-6">
	    <div class="panel panel-primary">
		<div class="panel-heading">
		    Contact Information
		</div>
		<div class="panel-body">
                    <table class="table">
                        <tr>
			    <th>Company</th>
			    <td><a href="{% url 'crm:company_list' %}">{{ opportunity.company }}</a></td>
			</tr>
                        <tr>
			    <th>Address</th>
			    <td>{{ opportunity.company.address1 }}</td>
			    <td>{{ opportunity.company.address2 }}</td>
			</tr>
                        <tr>
			    <th>City</th>
			    <td>{{ opportunity.company.city }}</td>
			</tr>
                        <tr>
			    <th>State, ZIP</th>
			    <td>{{ opportunity.company.state }}, {{ opportunity.company.zipcode }}</td>
			</tr>
                        <tr>
			    <th>Phone</th>
			    <td>{{ opportunity.company.phone }}</td>
			</tr>
                        <tr>
			    <th>Website</th>
			    <td><a href="{{ opportunity.company.website }}">{{ opportunity.company.website }}</a></td>
			</tr>
		    </table>
		</div>
	    </div>
	</div>
	
	<div class="col-lg-6">
	    <div class="panel panel-info">
		<div class="panel-heading">
		    Map
		</div>
	    	<div class="panel-body">
                    <center><div id="map" style="width: auto; height: 300px;"></div></center>
                    <script>
                        var map;
                        function initMap() {
                            address = '{{ opportunity.company.address1 }} {{ opportunity.company.address2 }}, {{ opportunity.company.city }}, {{ opportunity.company.state }} {{ opportunity.company.zipcode }}' ;
                            var geocoder  = new google.maps.Geocoder();
                            geocoder.geocode({ 'address': address}, function(results, status) {
                                var c = results[0].geometry.location;
                                latitude  = c.lat();
                                longitude = c.lng();
                                map = new google.maps.Map(document.getElementById('map'), {
                                    center: {lat: latitude, lng: longitude},
                                    scrollwheel: false,
                                    zoom: 14,
                                });
                                var marker = new google.maps.Marker({
                                    map: map,
                                    position: {lat: latitude, lng: longitude},
                                    title: 'Opportunity Name',
                                });
                            });
                        }
                    </script>
                    <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyDxCDEfKuCyTVE-Ex43CG5PQec_Uc5CiQQ&callback=initMap" async defer></script>
		</div>
	    </div>
	</div>
    </div>
    <div class="row">
        <div class="col-lg-6">
	    <div class="panel panel-info">
		<div class="panel-heading">
		    Call Log for {{ opportunity.company }}.
		    <span class="text-right pull-right">
			<a href="{% url 'crm:calllog_list' %}" class="btn btn-info  btn-sm mdi-action-list" style="margin-top: -7px;" title="List All Call Logs"></a>
		    </span>
		</div>
		<div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Note</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
			    {% if opportunity.calllog_set %}
                                {% for calllog in opportunity.calllog_set.all %}
				    <tr>
				        <td>{{ calllog.user }}</td>
				        <td>{{ calllog.note }}</td>
				        <td>{{ calllog.date|date:"j M Y" }}</td>
				    <tr>
			        {% endfor %}
			    {% endif %}
			</tbody>
		    </table>
		</div>
	    </div>
        </div>

        <div class="col-lg-6">
	    <div class="panel panel-primary">
		<div class="panel-heading">
		    Stage History
		</div>
		<div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Stage</th>
                                <th>User</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for stage in opportunity.opportunitystage_set.all %}
				<tr>
				    <td>{{ stage.stage }}</td>
				    <td>{{ stage.user }}</td>
				    <td>{{ stage.time_stamp|date:"j M Y" }}</td>
				<tr>
			    {% endfor %}
			</tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>
{% endblock content %}